In [1]:
"""
Created on Sat Dec 5 
@author: jing0703

Data source: 
https://www.metoffice.gov.uk/research/climate/maps-and-data/historic-station-data

Data format:
   1914   1    5.2     0.7    ---     52.0    ---
   1914   2    9.2     3.5    ---     28.0    ---
   1914   3   ---     ---     ---     ---     ---

Step:
1. Load and parse UK Weather Station History data 
2. Combine all stations so can run queries across all stations and all time periods 
3. Summary statistics for stations

Package:
Spark: 2.3.2
Python: 3.6.4
"""

def main():
    """
    main function to parse, clean up and analyze data
    """
    # create empty list to append data and row count for each station
    df_all = []
    station_count = []
    station_list =  ["aberporth", 
                     "armagh", 
                     "ballypatrick", 
                     "bradford", 
                     "braemar", 
                     "camborne", 
                     "cambridge", 
                     "cardiff", 
                     "chivenor", 
                     "dunstaffnage", 
                     "durham", 
                     "eastbourne", 
                     "eskdalemuir", 
                     "heathrow", 
                     "hurn", 
                     "lerwick", 
                     "leuchars", 
                     "whitby", 
                     "cwmystwyth", 
                     "lowestoft", 
                     "manston", 
                     "nairn", 
                     "newtonrigg", 
                     "oxford", 
                     "paisley", 
                     "ringway", 
                     "rossonwye", 
                     "shawbury", 
                     "sheffield", 
                     "southampton", 
                     "stornoway", 
                     "suttonbonington", 
                     "tiree", 
                     "valley", 
                     "waddington", 
                     "wickairport", 
                     "yeovilton"]
    
    start_time = timeit.default_timer()
    
    # read data for each station and append to list
    for station in station_list:
        url = f"https://www.metoffice.gov.uk/pub/data/weather/uk/climate/stationdata/{station}data.txt"
        sc.addFile(url)
        rdd = sc.textFile("file://"+ SparkFiles.get(f"{station}data.txt"))
        df= read_data(rdd, station)
        station_count.append(df.count())
        df_all.append(df)

    # create dict for row count of each station
    station_count = dict(zip(station_list, station_count))
    print("Row count for each station:", station_count)

    # union list of station data into complete df as all history data
    df_complete = reduce(DataFrame.unionAll, df_all).cache()
    
    # climate data analysis for question 4
    station_history_rank(df_complete)
    station_rain_sun_rank(df_complete)
    worst_rain_best_sun(df_complete)
    may_avg(df_complete)
    best_worst_year_may_climate(df_complete)
    
    # remove cached df
    del df_complete
    
    # finish timing program 
    end_time = timeit.default_timer()
    print(f"Program duration: {(end_time - start_time)}s")


def read_data(rdd, station):
    """
    function to remove header line, special character and provisional data
    """
    # list of df column name
    new_colnames = ["station", "year", "month", "tmax", "tmin", "af", "rain", "sun"]
    
    # find the index for the end of header and  filter out header & special character 
    head_index = rdd.zipWithIndex().lookup("              degC    degC    days      mm   hours")
    cli_data = rdd.zipWithIndex()\
                  .filter(lambda row_index: row_index[1] > head_index[0]).keys()\
                  .filter(lambda x: any(e not in x for e in ["*", "#", "$"])) 
    
    # split rdd, add station name, convert to df  
    line_df = cli_data.map(lambda line: (station, line.split(" "))).toDF(("station", "data"))
    
    # remove empty array from data column 
    # for spark >= 2.4 use array_remove function
    # from pyspark.sql.functions import array_remove
    # line_split.withColumn("data", array_remove("data", ""))
    drop_array = udf(drop_from_array, ArrayType(StringType()))
    
    # remove rows with extra character for provisional data
    df = line_df.withColumn("data", drop_array("data", lit(""))).filter(size("data") == 7)
    
    # split column data to multiple columns and rename new column
    df1 = df.select([df.station] + [df.data[i] for i in range(7)])
    df2 = df1.toDF(*new_colnames)\
          .replace("---", None)\
          .na.fill({"tmax": 0.0, "tmin": 0.0, "af": 0, "rain": 0.0, "sun": 0.0})\
          .withColumn("year",col("year").cast("integer"))\
          .withColumn("month",col("month").cast("integer"))\
          .withColumn("tmax",col("tmax").cast("float"))\
          .withColumn("tmin",col("tmin").cast("float"))\
          .withColumn("af",col("af").cast("integer"))\
          .withColumn("rain",col("rain").cast("float"))\
          .withColumn("sun",col("sun").cast("float")) \
          .cache() 

    return df2   


def drop_from_array(arr, item):
    """
    function to remove item from array
    """
    return [x for x in arr if x != item]


def round_column(col_names):
    """
    function to round float from multiple columns
    """
    def inner(df):
        for col_name in col_names:
            df = df.withColumn(
                col_name,
                round(df[col_name], 2)
            )
        return df
    return inner



def station_history_rank(df_complete):
    """
    a. Rank stations by how long they have been online
    """
    print("Rank stations by how long they have been online:")
    
    # groupby station & get earliest year/ month by agg
    df_online = df_complete.groupBy("station") \
        .agg(
             min("year").alias("online_y"), \
             min("month").alias("online_m") \
         ) \
        .orderBy("online_y", "online_m")
        
    # get dense rank of online time with window and ranking functions
    window = Window.orderBy(asc("online_y"), asc("online_m"))

    df_online_rank = df_online.withColumn(
        "online_time_rank", 
        dense_rank().over(window)
    ).show(37, truncate = False)



def station_rain_sun_rank(df_complete):
    """
    b. Rank stations by rainfall and / or sunshine
    """
    
    print("Station rank by total sunshine and rain fall:")
    df_rain_sun = df_complete.groupBy("station") \
                             .agg(
                                 sum("rain").alias("total_rainfall"),\
                                 sum("sun").alias("total_sunshine")
                             ) \
                             .orderBy("total_rainfall", "total_sunshine")

    rain_window = Window.orderBy(desc("total_rainfall"))
    sun_window = Window.orderBy(desc("total_sunshine"))
    
    df_rain_sun_rank = df_rain_sun.withColumn(
                                    "rainfall_rank", 
                                    dense_rank().over(rain_window)
                                 ).withColumn(
                                    "sunshine_rank", 
                                    dense_rank().over(sun_window)
                                 )
    round_column(["total_rainfall", "total_sunshine"])(df_rain_sun_rank).show(37, truncate = False)
    



def worst_rain_best_sun(df_complete):
    """
    c. When was the worst rainfall and / or best sunshine for each station
    
    """
    print("Worst rainfall for each station:")
    df_worst_rain = df_complete.withColumn("year_month", concat(col("year"), lit("-"), col("month")))\
                       .select(["station", "rain", "year_month"])\
                       .groupBy("station", "year_month") \
                       .agg(
                         sum("rain").alias("total_rainfall")
                       ) \
                       .groupBy("station") \
                       .agg(max(struct(col("total_rainfall"), col("year_month"))).alias("max_rain")) \
                       .select(col("station"), col("max_rain.year_month"), col("max_rain.total_rainfall")) \
                       .orderBy(desc("max_rain.total_rainfall")) 

    round_column(["total_rainfall"])(df_worst_rain).show(37, truncate = False)
    
    print("Best sunshine for each station:")
    df_best_sun = df_complete.withColumn("year_month", concat(col("year"), lit("-"), col("month")))\
                   .select(["station", "sun", "year_month"])\
                   .groupBy("station", "year_month") \
                   .agg(
                     sum("sun").alias("total_sunshine")
                   ) \
                   .groupBy("station") \
                   .agg(max(struct(col("total_sunshine"), col("year_month"))).alias("max_sun")) \
                   .select(col("station"), col("max_sun.year_month"), col("max_sun.total_sunshine")) \
                   .orderBy(desc("max_sun.total_sunshine")) 
                
    round_column(["total_sunshine"])(df_best_sun).show(37, truncate = False)


def may_avg(df_complete):
    """
    d. What are the averages for May across all stations
    
    """
    print("Average for May across all stations:")
    df_may_avg = df_complete.where(col("month") ==5) \
                            .agg(
                                avg("tmax").alias("avg_tmax"), \
                                avg("tmin").alias("avg_tmin"), \
                                avg("af").alias("avg_af"), \
                                avg("rain").alias("avg_rain"), \
                                avg("sun").alias("avg_sun") \
                            )
    round_column(["avg_tmax", "avg_tmin", "avg_af", "avg_rain", "avg_sun"])(df_may_avg).show(truncate = False)


def best_worst_year_may_climate(df_complete):
    """
    d. what was the best / worst years for May across all stations
    """
    
    # create df for avg climate of May across all stations and groupby year
    df_may_avg = df_complete.where(col("month") ==5) \
                            .groupBy("year") \
                            .agg(
                                avg("tmax").alias("avg_tmax"), \
                                avg("tmin").alias("avg_tmin"), \
                                avg("af").alias("avg_af"), \
                                avg("rain").alias("avg_rain"), \
                                avg("sun").alias("avg_sun") \
                            ) \
                            .orderBy("year").cache()
                
    # create window by asc & desc for average temp/ af/ sunshine/ rainfall
    tmax_window = Window.orderBy(desc("avg_tmax"))
    tmin_window = Window.orderBy(asc("avg_tmin"))
    af_desc_window = Window.orderBy(desc("avg_af"))
    af_asc_window = Window.orderBy(asc("avg_af"))
    sun_desc_window = Window.orderBy(desc("avg_sun"))
    sun_asc_window = Window.orderBy(asc("avg_sun"))
    rain_desc_window = Window.orderBy(desc("avg_rain"))
    rain_asc_window = Window.orderBy(asc("avg_rain"))
    
    print("Best and worst year of temperature for May:")
    may_tmax_max = df_may_avg.withColumn(
                            "tmax_rank", 
                            dense_rank().over(tmax_window)
                          ).select("year", "avg_tmax") \
                          .filter(col("tmax_rank") == 1) \
                          .withColumnRenamed("avg_tmax","may_temp_max") \
                          .withColumn("may_temp_max", round("may_temp_max", 2)) \
                          .show()
                
    may_tmin_min = df_may_avg.withColumn(
                                "tmin_rank", 
                                dense_rank().over(tmin_window)
                              ).select("year", "avg_tmin") \
                              .filter(col("tmin_rank") == 1) \
                              .withColumnRenamed("avg_tmin","may_temp_min") \
                              .withColumn("may_temp_min", round("may_temp_min", 2)) \
                              .show()
                    
    print("Best and worst year of days of air frost for May:")
    may_af_max = df_may_avg.withColumn(
                            "af_rank", 
                            dense_rank().over(af_desc_window)
                        ).select("year", "avg_af") \
                        .filter(col("af_rank") == 1) \
                        .withColumnRenamed("avg_af","may_af_max") \
                        .withColumn("may_af_max", round("may_af_max", 2)) \
                        .show()


    may_af_min = df_may_avg.withColumn(
                              "af_rank", 
                              dense_rank().over(af_asc_window)
                            ).select("year", "avg_af") \
                            .filter(col("af_rank") == 1) \
                            .withColumnRenamed("avg_af","may_af_min").show()
            
    print("Best and worst year of sunshine for May:")
    may_sun_max = df_may_avg.withColumn(
                            "sun_rank", 
                            dense_rank().over(sun_desc_window)
                        ).select("year", "avg_sun") \
                        .filter(col("sun_rank") == 1) \
                        .withColumnRenamed("avg_sun","may_sun_max") \
                        .withColumn("may_sun_max", round("may_sun_max", 2)) \
                        .show()

    may_sun_min = df_may_avg.withColumn(
                                "sun_rank", 
                                dense_rank().over(sun_asc_window)
                             ).select("year", "avg_sun") \
                            .filter(col("sun_rank") == 1) \
                            .withColumnRenamed("avg_sun","may_sun_min").show()
            
    print("Best and worst year of rainfall for May:")
    may_rain_max = df_may_avg.withColumn(
                            "rain_rank", 
                            dense_rank().over(rain_desc_window)
                        ).select("year", "avg_rain") \
                        .filter(col("rain_rank") == 1) \
                        .withColumnRenamed("avg_rain","may_rain_max") \
                        .withColumn("may_rain_max", round("may_rain_max", 2)) \
                        .show()


    may_rain_min = df_may_avg.withColumn(
                                "rain_rank", 
                                dense_rank().over(rain_asc_window)
                             ).select("year", "avg_rain") \
                             .filter(col("rain_rank") == 1) \
                             .withColumnRenamed("avg_rain","may_rain_min") \
                             .withColumn("may_rain_min", round("may_rain_min", 2)) \
                             .show()

In [2]:
if __name__ == '__main__':
    from pyspark import SparkContext, SparkFiles
    from pyspark.conf import SparkConf
    from pyspark.sql import SparkSession, SQLContext, DataFrame
    from pyspark.sql.functions import *
    from pyspark.sql.types import *
    from pyspark.sql.window import Window  
    from functools import reduce
    import timeit
    
    # define Spark configration 
    conf = SparkConf().setAppName("Spark Transformation App")
    conf.set("spark.excutor.memoryOverhead", "4096")
    conf.set("spark.driver.memoryOverhead", "4096")
    conf.set("spark.driver.memoryOverhead", "4096")
    conf.set("spark.dynamicAllocation.executorIdleTimeout", "60")
    conf.set("spark.dynamicAllocation.minExecutors", "2")
    conf.set("spark.dynamicAllocation.initialExecutors", "2")
    conf.set("spark.sql.shuffle.partitions", "200")
    conf.set("spark.sql.autoBroadcastJoinThreshold", 1024 * 1024 * 10)
    conf.set("spark.yarn.maxAppAttempts", 1)
    conf.set("spark.yarn.max.executor.failures", 100)
    conf.set("spark.sql.broadcastTimeout", 36000)
    
    # define Spark driver session
    spark = SparkSession \
            .builder.master("local[*]") \
            .config(conf = conf) \
            .appName("ClimateAnalysis") \
            .getOrCreate()
            
    sc = spark.sparkContext
    sc.setLogLevel("ERROR")
    
    main()

Row count for each station: {'aberporth': 948, 'armagh': 2004, 'ballypatrick': 701, 'bradford': 1344, 'braemar': 732, 'camborne': 496, 'cambridge': 732, 'cardiff': 508, 'chivenor': 768, 'dunstaffnage': 582, 'durham': 1680, 'eastbourne': 732, 'eskdalemuir': 1308, 'heathrow': 864, 'hurn': 756, 'lerwick': 1069, 'leuchars': 756, 'whitby': 521, 'cwmystwyth': 618, 'lowestoft': 1258, 'manston': 941, 'nairn': 1067, 'newtonrigg': 732, 'oxford': 2004, 'paisley': 732, 'ringway': 706, 'rossonwye': 1069, 'shawbury': 888, 'sheffield': 1644, 'southampton': 1743, 'stornoway': 1758, 'suttonbonington': 732, 'tiree': 1104, 'valley': 1069, 'waddington': 876, 'wickairport': 1272, 'yeovilton': 664}
Rank stations by how long they have been online:
+---------------+--------+--------+----------------+
|station        |online_y|online_m|online_time_rank|
+---------------+--------+--------+----------------+
|oxford         |1853    |1       |1               |
|armagh         |1853    |1       |1               |
|southampton    |1855    |1       |2               |
|stornoway      |1873    |1       |3               |
|durham         |1880    |1       |4               |
|sheffield      |1883    |1       |5               |
|bradford       |1908    |1       |6               |
|eskdalemuir    |1911    |1       |7               |
|wickairport    |1914    |1       |8               |
|lowestoft      |1914    |1       |8               |
|tiree          |1928    |1       |9               |
|valley         |1930    |1       |10              |
|rossonwye      |1930    |1       |10              |
|lerwick        |1930    |1       |10              |
|nairn          |1931    |1       |11              |
|manston        |1934    |1       |12              |
|aberporth      |1941    |1       |13              |
|shawbury       |1946    |1       |14              |
|ringway        |1946    |1       |14              |
|waddington     |1947    |1       |15              |
|heathrow       |1948    |1       |16              |
|chivenor       |1951    |1       |17              |
|leuchars       |1957    |1       |18              |
|hurn           |1957    |1       |18              |
|eastbourne     |1959    |1       |19              |
|suttonbonington|1959    |1       |19              |
|newtonrigg     |1959    |1       |19              |
|paisley        |1959    |1       |19              |
|cwmystwyth     |1959    |1       |19              |
|braemar        |1959    |1       |19              |
|cambridge      |1959    |1       |19              |
|ballypatrick   |1961    |1       |20              |
|yeovilton      |1964    |1       |21              |
|dunstaffnage   |1971    |1       |22              |
|whitby         |1976    |1       |23              |
|cardiff        |1977    |1       |24              |
|camborne       |1978    |1       |25              |
+---------------+--------+--------+----------------+

Station rank by total sunshine and rain fall:
+---------------+--------------+--------------+-------------+-------------+
|station        |total_rainfall|total_sunshine|rainfall_rank|sunshine_rank|
+---------------+--------------+--------------+-------------+-------------+
|southampton    |115856.1      |159483.6      |4            |1            |
|durham         |90892.1       |146785.7      |10           |2            |
|oxford         |108810.9      |138595.4      |6            |3            |
|lowestoft      |54473.6       |133551.4      |19           |4            |
|bradford       |94938.5       |122385.4      |9            |5            |
|valley         |75982.4       |114236.7      |14           |6            |
|rossonwye      |57253.0       |114024.5      |17           |7            |
|sheffield      |109633.6      |111331.7      |5            |8            |
|armagh         |137511.2      |111241.8      |3            |9            |
|eastbourne     |47484.4       |108923.7      |25           |10           |
|tiree          |105416.4      |104545.4      |7            |11           |
|nairn          |51976.9       |102341.5      |22           |12           |
|eskdalemuir    |175629.9      |92600.8       |2            |13           |
|waddington     |44352.0       |92573.3       |29           |14           |
|aberporth      |72063.3       |92115.7       |15           |15           |
|stornoway      |175691.5      |91017.3       |1            |16           |
|lerwick        |102209.1      |82890.2       |8            |17           |
|ringway        |35711.7       |81066.4       |35           |18           |
|shawbury       |49383.0       |77524.1       |24           |19           |
|heathrow       |43612.4       |76115.6       |30           |20           |
|manston        |45171.1       |75545.9       |27           |21           |
|cambridge      |32427.0       |75123.2       |36           |22           |
|leuchars       |43075.2       |73255.8       |31           |23           |
|paisley        |61538.7       |65273.8       |16           |24           |
|wickairport    |82339.5       |61039.6       |12           |25           |
|hurn           |52568.0       |60678.3       |21           |26           |
|suttonbonington|36038.4       |56179.8       |34           |27           |
|cwmystwyth     |87940.0       |55835.6       |11           |28           |
|braemar        |51336.0       |51240.8       |23           |29           |
|camborne       |44589.1       |46557.2       |28           |30           |
|whitby         |26932.4       |33397.6       |37           |31           |
|chivenor       |54881.9       |33124.0       |18           |32           |
|ballypatrick   |40794.3       |32852.4       |32           |33           |
|yeovilton      |40106.0       |30189.6       |33           |34           |
|newtonrigg     |53599.7       |29681.8       |20           |35           |
|cardiff        |47300.5       |26453.3       |26           |36           |
|dunstaffnage   |78685.4       |22579.5       |13           |37           |
+---------------+--------------+--------------+-------------+-------------+

Worst rainfall for each station:
+---------------+----------+--------------+
|station        |year_month|total_rainfall|
+---------------+----------+--------------+
|eskdalemuir    |2015-12   |568.8         |
|cwmystwyth     |2009-11   |425.4         |
|dunstaffnage   |2011-12   |417.8         |
|stornoway      |1898-12   |377.5         |
|newtonrigg     |2015-12   |329.4         |
|braemar        |2015-12   |316.8         |
|ballypatrick   |2008-8    |313.0         |
|lerwick        |2015-1    |302.4         |
|paisley        |2006-12   |298.9         |
|sheffield      |2007-6    |285.6         |
|southampton    |1903-10   |280.7         |
|camborne       |1978-12   |276.7         |
|manston        |1939-10   |271.8         |
|tiree          |2015-12   |268.6         |
|cardiff        |2000-10   |267.6         |
|bradford       |2007-6    |261.4         |
|eastbourne     |2000-10   |261.1         |
|hurn           |1960-10   |258.9         |
|valley         |2015-12   |254.2         |
|wickairport    |2006-10   |234.6         |
|chivenor       |2009-7    |233.0         |
|aberporth      |1954-11   |232.3         |
|armagh         |1870-10   |226.4         |
|nairn          |1995-9    |222.4         |
|waddington     |1956-8    |217.5         |
|leuchars       |2004-8    |215.6         |
|durham         |1888-7    |209.7         |
|ringway        |2000-10   |193.6         |
|oxford         |1875-10   |192.9         |
|yeovilton      |2002-11   |192.4         |
|whitby         |2010-11   |189.0         |
|rossonwye      |1959-12   |186.0         |
|suttonbonington|1977-2    |176.5         |
|heathrow       |1987-10   |174.8         |
|shawbury       |1976-9    |174.7         |
|cambridge      |2005-9    |166.2         |
|lowestoft      |1939-10   |163.9         |
+---------------+----------+--------------+

Best sunshine for each station:
+---------------+----------+--------------+
|station        |year_month|total_sunshine|
+---------------+----------+--------------+
|southampton    |1911-7    |350.3         |
|aberporth      |1955-7    |342.1         |
|valley         |1955-7    |341.4         |
|chivenor       |1957-6    |336.8         |
|eastbourne     |2006-7    |335.3         |
|tiree          |1975-5    |329.1         |
|manston        |1989-5    |326.3         |
|hurn           |1975-6    |320.1         |
|lowestoft      |1976-6    |314.4         |
|heathrow       |1989-5    |310.1         |
|rossonwye      |2006-7    |309.6         |
|camborne       |1990-7    |308.4         |
|cardiff        |1995-8    |305.4         |
|waddington     |2006-7    |304.5         |
|oxford         |2006-7    |303.7         |
|bradford       |1957-6    |300.1         |
|whitby         |2006-7    |299.9         |
|ringway        |1957-6    |297.5         |
|durham         |1940-6    |297.0         |
|stornoway      |1994-5    |294.1         |
|shawbury       |1957-6    |292.9         |
|yeovilton      |1995-8    |292.2         |
|sheffield      |2006-7    |290.8         |
|cambridge      |1962-6    |289.6         |
|ballypatrick   |1975-5    |279.3         |
|eskdalemuir    |1957-6    |275.9         |
|lerwick        |1948-5    |271.5         |
|dunstaffnage   |1995-6    |270.9         |
|suttonbonington|1960-6    |265.4         |
|newtonrigg     |1960-6    |265.3         |
|braemar        |1992-5    |265.2         |
|cwmystwyth     |1976-8    |260.2         |
|paisley        |1995-6    |259.9         |
|armagh         |1940-6    |256.0         |
|wickairport    |1948-5    |252.9         |
|leuchars       |1989-7    |252.6         |
|nairn          |1940-6    |249.1         |
+---------------+----------+--------------+

Average for May across all stations:

+--------+--------+------+--------+-------+
|avg_tmax|avg_tmin|avg_af|avg_rain|avg_sun|
+--------+--------+------+--------+-------+
|14.46   |6.53    |0.58  |55.95   |143.45 |
+--------+--------+------+--------+-------+

Best and worst year of temperature for May:
+----+------------+
|year|may_temp_max|
+----+------------+
|1868|       18.73|
+----+------------+

+----+------------+
|year|may_temp_min|
+----+------------+
|1854|        2.85|
+----+------------+

Best and worst year of days of air frost for May:
+----+----------+
|year|may_af_max|
+----+----------+
|1979|      3.34|
+----+----------+

+----+----------+
|year|may_af_min|
+----+----------+
|1853|       0.0|
|1858|       0.0|
|1859|       0.0|
|1860|       0.0|
|1862|       0.0|
|1863|       0.0|
|1864|       0.0|
|1865|       0.0|
|1868|       0.0|
|1869|       0.0|
|1871|       0.0|
|1875|       0.0|
|1878|       0.0|
|1884|       0.0|
|1889|       0.0|
|1890|       0.0|
|1893|       0.0|
|1895|       0.0|
|1908|       0.0|
|1911|       0.0|
+----+----------+
only showing top 20 rows

Best and worst year of sunshine for May:
+----+-----------+
|year|may_sun_max|
+----+-----------+
|1948|     234.22|
+----+-----------+

+----+-----------+
|year|may_sun_min|
+----+-----------+
|1853|        0.0|
|1854|        0.0|
|1855|        0.0|
|1856|        0.0|
|1857|        0.0|
|1858|        0.0|
|1859|        0.0|
|1860|        0.0|
|1861|        0.0|
|1862|        0.0|
|1863|        0.0|
|1864|        0.0|
|1865|        0.0|
|1866|        0.0|
|1867|        0.0|
|1868|        0.0|
|1869|        0.0|
|1870|        0.0|
|1871|        0.0|
|1872|        0.0|
+----+-----------+
only showing top 20 rows

Best and worst year of rainfall for May:
+----+------------+
|year|may_rain_max|
+----+------------+
|1862|      109.57|
+----+------------+

+----+------------+
|year|may_rain_min|
+----+------------+
|1871|       10.67|
+----+------------+

Program duration: 108.89527858234942s